# Generated by Django 3.0.4 on 2020-06-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dna',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dna',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
