# Generated by Django 3.0.4 on 2020-06-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0003_auto_20200613_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna',
            name='file',
            field=models.TextField(null=True),
        ),
    ]
