# Generated by Django 3.0.4 on 2020-06-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0005_auto_20200613_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna',
            name='file_path',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
