# Generated by Django 3.0.4 on 2020-06-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0009_auto_20200614_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna',
            name='percentage_a',
            field=models.IntegerField(null=True),
        ),
    ]
