# Generated by Django 3.0.4 on 2020-06-17 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0011_auto_20200614_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dna',
            new_name='Sequence',
        ),
    ]
