# Generated by Django 3.0.4 on 2020-06-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0014_auto_20200618_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='ratio_g_c_graph_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
