# Generated by Django 3.0.4 on 2020-06-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0015_sequence_ratio_g_c_graph_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='dna_walk_graph_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='ratio_g_c_graph_data',
            field=models.TextField(null=True),
        ),
    ]
