# Generated by Django 3.0.4 on 2020-06-13 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('file', models.TextField(null=True)),
                ('file_path', models.FileField(upload_to='')),
                ('nb_bases', models.TextField(max_length=500, null=True)),
                ('nb_a', models.TextField(max_length=50, null=True)),
                ('nb_c', models.TextField(max_length=50, null=True)),
                ('nb_g', models.TextField(max_length=50, null=True)),
                ('nb_t', models.TextField(max_length=50, null=True)),
                ('percentage_a', models.TextField(max_length=50, null=True)),
                ('percentage_c', models.TextField(max_length=50, null=True)),
                ('percentage_g', models.TextField(max_length=50, null=True)),
                ('percentage_t', models.TextField(max_length=50, null=True)),
                ('percentage_gc', models.TextField(max_length=50, null=True)),
                ('percentage_at', models.TextField(max_length=50, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
        ),
    ]
