# Generated by Django 3.0.4 on 2020-06-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200613_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna',
            name='file',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
