# Generated by Django 3.0.4 on 2020-06-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200613_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna',
            name='nb_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dna',
            name='nb_bases',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dna',
            name='nb_c',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dna',
            name='nb_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dna',
            name='nb_t',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dna',
            name='percentage_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dna',
            name='percentage_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dna',
            name='percentage_c',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dna',
            name='percentage_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dna',
            name='percentage_gc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dna',
            name='percentage_t',
            field=models.IntegerField(null=True),
        ),
    ]
