# Generated by Django 3.0.4 on 2020-05-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200528_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna',
            name='file',
            field=models.BinaryField(editable=True),
        ),
    ]
