# Generated by Django 3.0.4 on 2020-05-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200528_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna',
            name='file',
            field=models.BinaryField(),
        ),
    ]
