# Generated by Django 3.0.4 on 2020-05-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200528_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='dna',
            name='file_path',
            field=models.FileField(default='d', upload_to=''),
            preserve_default=False,
        ),
    ]
