# Generated by Django 3.0.4 on 2020-06-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200617_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='file',
            new_name='sequence',
        ),
    ]
