# Generated by Django 3.0.4 on 2020-06-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200528_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='dna',
            name='nb_a',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dna',
            name='nb_bases',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dna',
            name='nb_c',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dna',
            name='nb_g',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dna',
            name='nb_t',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dna',
            name='percentage_a',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dna',
            name='percentage_at',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dna',
            name='percentage_c',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dna',
            name='percentage_g',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dna',
            name='percentage_gc',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dna',
            name='percentage_t',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
