# Generated by Django 3.0.4 on 2020-06-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200618_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='sequence',
            new_name='file',
        ),
    ]
