# Generated by Django 3.0.4 on 2020-06-09 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200609_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='dna',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
    ]
