# Generated by Django 3.0.4 on 2020-06-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_dna_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna',
            name='nb_bases',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
