# Generated by Django 3.1 on 2020-08-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20200621_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='dna_walk_graph_data',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='nb_a',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='nb_bases',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='nb_c',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='nb_g',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='nb_t',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='percentage_a',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='percentage_at',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='percentage_c',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='percentage_g',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='percentage_gc',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='percentage_t',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='ratio_g_c_graph_data',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='user',
        ),
    ]
