# Generated by Django 3.0.4 on 2020-06-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_sequence_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='user_id',
            new_name='user',
        ),
    ]
